spring.application.name=demo


# ==========================
# DATABASE
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5433/kbase_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver



# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# ==========================
# JWT
# ==========================

jwt.secret=kbase_secret_key_123456_kbase_secret_key_123456



# ==========================
# FILE UPLOAD
# ==========================

file.upload-dir=uploads



spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=60MB